name: PR Checks

on:
  pull_request:
    branches: ['**']

permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install and build
        run: npm install

      - name: Prettier Check
        run: npm run prettier:check

      - name: Validate TypeScript
        run: npm run typecheck

      - name: Validate ESLint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install and build
        run: npm install

      - name: Unit tests
        run: npm run test

      - name: Cypress e2e tests
        run: npm run e2e:headless

      - name: Cypress component tests
        run: npm run components:headless

  performance:
    name: Performance test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install and build
        run: npm install

      - name: Reassure tests
        run: yarn --cwd packages/reassure-compare test

      - name: Run performance tests
        run: ./reassure-tests.sh

      - name: Run Danger.js
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
