name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: ['**']

jobs:
  build-validate-pref-tests:
    name: Build, validate & run performance tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install and build
        run: yarn install --force

      - name: Validate TypeScript
        run: npm run typecheck

      - name: Validate ESLint
        run: npm run lint

      - name: Unit tests
        run: npm run test

      - name: Cypress e2e tests
        run: npm run e2e

      - name: Cypress component tests
        run: npm run cypress:headless

      - name: Reassure tests
        run: yarn --cwd packages/reassure-compare test

      - name: Run performance tests
        run: cd examples/native && ./reassure-tests.sh

      - name: Run Danger.js
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
